<?php

class ApacheConfigTest extends PHPUnit_Framework_TestCase
{
    private static function trimAllLines($str)
    {
	// also removes empty lines
	return preg_replace('/[\s]*[\n][\s]*/s', "\n", $str);
    }
	
    public function testCreateConfigWithoutAlias()
    {
	$apacheConfigService = new services\ApacheConfigDirectory();

	$actual = $apacheConfigService->createConfig('test', array('test1'));
	$this->assertNotNull($actual);

$expected = <<<EOF
# This file was auto-generated by deployer, do not edit!
  <Directory /var/www/test/public>
  AllowOverride All
  </Directory>

  <VirtualHost *>
  DocumentRoot /var/www/test/public
  ServerName test1
  ErrorLog /var/log/apache2/test-error_log
  CustomLog /var/log/apache2/test-access_log combined env=!dontlog
  </VirtualHost>
EOF;

	$expected = self::trimAllLines($expected);
	$actual = self::trimAllLines($actual);

	$this->assertEquals($expected, $actual);
    }


    public function testCreateConfigWithAlias()
    {
	$apacheConfigService = new services\ApacheConfigDirectory();

	$actual = $apacheConfigService->createConfig('test', array('test1', 'test2'));
	$this->assertNotNull($actual);

$expected = <<<EOF
# This file was auto-generated by deployer, do not edit!
  <Directory /var/www/test/public>
  AllowOverride All
  </Directory>

  <VirtualHost *>
  DocumentRoot /var/www/test/public
  ServerName test1
  ServerAlias test2
  ErrorLog /var/log/apache2/test-error_log
  CustomLog /var/log/apache2/test-access_log combined env=!dontlog
  </VirtualHost>
EOF;

	$expected = self::trimAllLines($expected);
	$actual = self::trimAllLines($actual);

	$this->assertEquals($expected, $actual);
    }

    public function testCreateConfigWithExtraConfig()
    {
	$apacheConfigService = new services\ApacheConfigDirectory();

	$actual = $apacheConfigService->createConfig('test', array('test1', 'test2'), 
		'Include /etc/phpmyadmin/apache.conf');
	$this->assertNotNull($actual);

$expected = <<<EOF
# This file was auto-generated by deployer, do not edit!
<Directory /var/www/test/public>
  AllowOverride All
</Directory>

<VirtualHost *>
  DocumentRoot /var/www/test/public
  ServerName test1
  ServerAlias test2
  ErrorLog /var/log/apache2/test-error_log
  CustomLog /var/log/apache2/test-access_log combined env=!dontlog
  Include /etc/phpmyadmin/apache.conf
</VirtualHost>
EOF;

	$expected = self::trimAllLines($expected);
	$actual = self::trimAllLines($actual);

	$this->assertEquals($expected, $actual);
    }


}

