<?php
namespace Application\Service;

class ApacheConfigDirectory
{
	function createConfig($siteName, $domainNames, $extraConfig = null)
	{
		$result =<<<EOF
# This file was auto-generated by deployer, do not edit!
<Directory /var/www/${siteName}/public>
	AllowOverride All
</Directory>

<VirtualHost *>
	DocumentRoot /var/www/${siteName}/public
	ServerName ${domainNames[0]}

EOF;

	if (count($domainNames) > 1)
	{
		$aliases = $domainNames;
		array_shift($aliases);
		$result .= "\tServerAlias ";
		$result .= implode(' ', $aliases);
		$result .= "\n";
	}

$result .= <<<EOF
	ErrorLog /var/log/apache2/${siteName}-error_log
	CustomLog /var/log/apache2/${siteName}-access_log combined env=!dontlog

EOF;

		if ($extraConfig)
		{
			$result .= $extraConfig;
			$result .= "\n";
		}

		$result .= "</VirtualHost>";

		return $result;
	}
}
